# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ChaosGame <- function(n_vertex, distance, iterations, rule = 0L) {
    .Call(`_ChaosGamePlot_ChaosGame`, n_vertex, distance, iterations, rule)
}

